import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Registration } from '@/types/registration';

// Helper function to convert registrations to CSV format
export const exportToCSV = (registrations: Registration[]) => {
  // Define CSV headers
  const headers = [
    'First Name',
    'Last Name',
    'Email',
    'Phone',
    'Institution',
    'Participant Type',
    'Status',
    'Created At'
  ].join(',');

  // Convert registrations to CSV rows
  const rows = registrations.map(reg => [
    reg.first_name,
    reg.last_name,
    reg.email,
    reg.phone || '',
    reg.institution,
    reg.participant_type,
    reg.status,
    new Date(reg.created_at).toLocaleDateString()
  ].map(field => `"${field}"`).join(','));

  // Combine headers and rows
  const csv = [headers, ...rows].join('\n');

  // Create and trigger download
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `registrations-${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Helper function to export registrations to PDF
export const exportToPDF = (registrations: Registration[]) => {
  const doc = new jsPDF();

  // Add title
  doc.setFontSize(16);
  doc.text('Registrations Report', 14, 15);
  doc.setFontSize(10);
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 14, 22);

  // Define table columns
  const columns = [
    'Name',
    'Email',
    'Phone',
    'Institution',
    'Type',
    'Status',
    'Created'
  ];

  // Prepare table data
  const data = registrations.map(reg => [
    `${reg.first_name} ${reg.last_name}`,
    reg.email,
    reg.phone || '',
    reg.institution,
    reg.participant_type,
    reg.status,
    new Date(reg.created_at).toLocaleDateString()
  ]);

  // Add table using autoTable
  autoTable(doc, {
    head: [columns],
    body: data,
    startY: 30,
    margin: { top: 25, bottom: 40 }, // Increased bottom margin for footer
    styles: { fontSize: 8 },
    headStyles: { fillColor: [41, 128, 185] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    didDrawPage: function(data) {
      // Add footer on each page
      const pageHeight = doc.internal.pageSize.height;
      const pageWidth = doc.internal.pageSize.width;
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128); // Gray color for footer
      
      // Footer text
      const footerText = "Generated by Quranic Seminar Web Platform | Akode Islamic Centre - Advancing Quranic Learning & Research";
      
      // Center the text by positioning it at the middle of the page
      doc.text(footerText, pageWidth / 2, pageHeight - 15, { align: 'center' });
      
      // Add divider line above footer
      doc.setDrawColor(200, 200, 200); // Light gray for the line
      doc.line(20, pageHeight - 20, pageWidth - 20, pageHeight - 20);
    }
  });

  // Save the PDF
  doc.save(`registrations-${new Date().toISOString().split('T')[0]}.pdf`);
}; 